/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class TtlStrCache {
  constructor()
  set(key: string, value: string): void
  get(key: string): string | null
  delete(key: string): void
  clear(): void
  has(key: string): boolean
  get length(): number
}
