/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class TtlStrCache {
  constructor()
  static default(): TtlStrCache
  set(key: string, value: string): void
  length(): number
}
