/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class TtlStrCache {
	constructor();
	static withTimeoutMs(timeoutMs: number): TtlStrCache;
	set(key: string, value: string): void;
	get(key: string): string | null;
	delete(key: string): void;
	clear(): void;
	has(key: string): boolean;
	/* Can use this to clear the table */
	get length(): number;
}
