name: Cargo + Node Tests

on:
  pull_request:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        node-version: [18.x]

    env:
      CARGO_TERM_COLOR: always

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install Cargo
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
          toolchain: stable
          target: x86_64-unknown-linux-gnu

      - name: Test (rust)
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Install dependencies (node)
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build --target x86_64-unknown-linux-gnu

      - name: Test (node)
        run: yarn test

      - run: rustup component add clippy
      - name: Rust clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
